### ISSUE TITLE
Unable to load XKT model when deploying the application

### ISSUE THREAD

**Issue by ctrlmaniac** [xeokit/xeokit-sdk#1080]
I'm having issues loading the XKT module. When I use VITE (with react) and runs the application locally, the model is loaded and displayed. I get the xkt file from an external url (http://localhost:3000/xktfile.xkt). However when I deploy the application, the xkt file is not loaded and chrome says that there is an error...

```
const baseUrl =
  import.meta.env.MODE == "development"
    ? "http://localhost:3000"
    : window.location.origin;

React.useEffect(() => {
    const viewer = new Viewer({
      canvasId: "model",
      transparent: true,
    });

    viewer.camera.zoom(5);
    viewer.cameraControl.followPointer = true;

    const xktLoader = new XKTLoaderPlugin(viewer);

    const model = xktLoader.load({
      id: "model",
      src: baseUrl + xkt,
      edges: true,
      backfaces: true,
    });

    model.on("loaded", () => {
      console.log("loaded");
    });

    // @ts-expect-error e invece sì
    viewer.scene.canvas.canvas.oncontextmenu = (e) => {
      if (!canvasContextMenu.enabled) return;
      e.preventDefault();

      const hit = viewer.scene.pick({ canvasPos: [e.layerX, e.layerY] });

      if (hit) {
        canvasContextMenu.context = { entity: hit.entity };
        canvasContextMenu.show(e.pageX, e.pageY);
      }
    };

    let lastEntity: any = null;

    // @ts-expect-error e invece sì
    viewer.scene.input.on("mousemove", (coords: any) => {
      const hit = viewer.scene.pick({ canvasPos: coords });

      if (hit) {
        if (!lastEntity || hit.entity?.id !== lastEntity.id) {
          if (lastEntity) lastEntity.highlighted = false;

          lastEntity = hit.entity;
          hit.entity!.highlighted = true;
        }
      } else if (lastEntity) {
        lastEntity.highlighted = false;
        lastEntity = null;
      }
    });
  }, [xkt]);

  return (
    <canvas id="model" style={{ height: "70vh", maxWidth: "100%" }}></canvas>
  );
```

The screenshot of the infinite loading when deploying the application:

![test bimfacility it_edifici_dettagli_1(iPhone SE)](https://github.com/xeokit/xeokit-sdk/assets/6809907/f0bbdeea-59da-4db4-84ef-0acb51a382fe)

and the chrome error is this one:

```
[xeokit plugin XKTLoader]: Loading .xkt V10
index-d933d978.js:679 Uncaught TypeError: Cannot read properties of undefined (reading 'inflate')
    at z5e (index-d933d978.js:679:166910)
    at Object.parse (index-d933d978.js:679:176488)
    at tC._parseModel (index-d933d978.js:679:181131)
    at index-d933d978.js:679:180645
    at c.onreadystatechange (index-d933d978.js:679:73006)
```

When inspecting the file it gives error to this function:

```
function z5e(t) {
        function e(r, n) {
            return r.length === 0 ? [] : Oy.inflate(r, n).buffer
        }
        return {
            metadata: JSON.parse(Oy.inflate(t.metadata, {
                to: "string"
            })),
            textureData: new Uint8Array(e(t.textureData)),
            eachTextureDataPortion: new Uint32Array(e(t.eachTextureDataPortion)),
            eachTextureAttributes: new Uint16Array(e(t.eachTextureAttributes)),
            positions: new Uint16Array(e(t.positions)),
            normals: new Int8Array(e(t.normals)),
            colors: new Uint8Array(e(t.colors)),
            uvs: new Float32Array(e(t.uvs)),
            indices: new Uint32Array(e(t.indices)),
            edgeIndices: new Uint32Array(e(t.edgeIndices)),
            eachTextureSetTextures: new Int32Array(e(t.eachTextureSetTextures)),
            matrices: new Float32Array(e(t.matrices)),
            reusedGeometriesDecodeMatrix: new Float32Array(e(t.reusedGeometriesDecodeMatrix)),
            eachGeometryPrimitiveType: new Uint8Array(e(t.eachGeometryPrimitiveType)),
            eachGeometryPositionsPortion: new Uint32Array(e(t.eachGeometryPositionsPortion)),
            eachGeometryNormalsPortion: new Uint32Array(e(t.eachGeometryNormalsPortion)),
            eachGeometryColorsPortion: new Uint32Array(e(t.eachGeometryColorsPortion)),
            eachGeometryUVsPortion: new Uint32Array(e(t.eachGeometryUVsPortion)),
            eachGeometryIndicesPortion: new Uint32Array(e(t.eachGeometryIndicesPortion)),
            eachGeometryEdgeIndicesPortion: new Uint32Array(e(t.eachGeometryEdgeIndicesPortion)),
            eachMeshGeometriesPortion: new Uint32Array(e(t.eachMeshGeometriesPortion)),
            eachMeshMatricesPortion: new Uint32Array(e(t.eachMeshMatricesPortion)),
            eachMeshTextureSet: new Int32Array(e(t.eachMeshTextureSet)),
            eachMeshMaterialAttributes: new Uint8Array(e(t.eachMeshMaterialAttributes)),
            eachEntityId: JSON.parse(Oy.inflate(t.eachEntityId, {
                to: "string"
            })),
            eachEntityMeshesPortion: new Uint32Array(e(t.eachEntityMeshesPortion)),
            eachTileAABB: new Float64Array(e(t.eachTileAABB)),
            eachTileEntitiesPortion: new Uint32Array(e(t.eachTileEntitiesPortion))
        }
    }
```

especially to

```
metadata: JSON.parse(Oy.inflate(t.metadata, {
                to: "string"
            })),
```

Why it doesn't load?

**Comment by pierretoussing** [comment]
@ctrlmaniac I am facing the same error. Could you elaborate what you mean by `solved it by splitting the code`? Thank you very much!

**Comment by ctrlmaniac** [comment]
> @ctrlmaniac I am facing the same error. Could you elaborate what you mean by `solved it by splitting the code`? Thank you very much!

I've juist imported the modules with lazy functionality

`const module = lazy(() => import('./module')`

**Comment by mbustamanteo** [comment]
Hello, just wanted to say I also ran into this issue when switching from `create-react-app` to `vite`.  The viewer would work OK on development but wouldn't load in production at all .

What worked for me was to use the following setting in `vite.config.js`
```
export default defineConfig(() => {
  return {
    rollupOptions: {
      output: {
        manualChunks: {
          xkt: ['@xeokit/xeokit-sdk']
        }
      }
    },
    ...
}
 ```
