### ISSUE TITLE
FIX: Scene#pick with excludeEntities throws an error

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1228]
**Describe the bug**
When we call viewer.scene.pick with `excludeEntities`

**To Reproduce**
1. Load XKT model
2. call `viewer.scene.pick` with `excludeEntities` option

Code snippet:

```js
const hit = viewer.scene.pick({
   canvasPos: coords,
   pickSurface: true,
   excludeEntities: Object.keys(libModel.objects),
});
```

This error is thrown

```
Uncaught TypeError: Cannot read properties of undefined (reading '2xX9VTSUL0YhFBdp$7i2HU')
    at getEntityIDMap (xeokit-sdk.es.js:26436:33)
    at Scene.pick (xeokit-sdk.es.js:28532:39)
    at Input.<anonymous> (xkt_vbo_Duplex.html:174:32)
    at Input.fire (xeokit-sdk.es.js:7937:38)
    at element.addEventListener._mouseDownListener (xeokit-sdk.es.js:18843:18)
getEntityIDMap @ xeokit-sdk.es.js:26436
pick @ xeokit-sdk.es.js:28532
(anonymous) @ xkt_vbo_Duplex.html:174
fire @ xeokit-sdk.es.js:7937
element.addEventListener._mouseDownListener @ xeokit-sdk.es.js:18843
```

**Expected behavior**
Elements are picked except provided entities

I tracked the error stack trace and it looks like in `getEntityIDMap`, it tries to find the entity in `scene.component` which doesn't exist

```js
function getEntityIDMap(scene, entityIds) {
    const map = {};
    let entityId;
    let entity;
    for (let i = 0, len = entityIds.length; i < len; i++) {
        entityId = entityIds[i];
        entity = scene.component[entityId];
        if (!entity) {
            scene.warn("pick(): Component not found: " + entityId);
            continue;
        }
        if (!entity.isEntity) {
            scene.warn("pick(): Component is not an Entity: " + entityId);
            continue;
        }
        map[entityId] = true;
    }
    return map;
}
```

**Comment by xeolabs** [comment]
Yip that's a typo - should be `scene.components`. - if you can do a PR, I'll merge. Thanks

**Comment by hamza-hajji** [comment]
@xeolabs done
