### ISSUE TITLE
Error thrown in TrianglesBatchingLayer

### ISSUE THREAD

**Issue by hamza-hajji** [xeokit/xeokit-sdk#1294]
**Describe the bug**

In the latest version 2.4.2-beta-41, loading a model throws an error that didn't throw before

**To Reproduce**
1. Load an XKT model

An error is thrown

```
Uncaught TypeError: Cannot set property aabb of #<TrianglesBatchingLayer> which has only a getter
    at new TrianglesBatchingLayer (xeokit-sdk.es.js:55715:1)
    at SceneModel._getVBOBatchingLayer (xeokit-sdk.es.js:77957:1)
    at SceneModel._createMesh (xeokit-sdk.es.js:77830:1)
    at SceneModel.createMesh (xeokit-sdk.es.js:77811:1)
    at load (xeokit-sdk.es.js:112170:1)
    at Object.parse (xeokit-sdk.es.js:112223:1)
    at XKTLoaderPlugin._parseModel (xeokit-sdk.es.js:113310:1)
```

**Expected behavior**
No error is thrown

**Screenshots**
![image](https://github.com/xeokit/xeokit-sdk/assets/26790341/0456a69b-10dc-41bd-acff-2fefeefcbfc2)

**Additional context**
Maybe adding a setter for aabb in TrianglesBatchingLayer class will solve this?

```js
get aabb() {
    if (this.aabbDirty) {
        math.collapseAABB3(this._aabb);
        for (let i = 0, len = this._meshes.length; i < len; i++) {
            math.expandAABB3(this._aabb, this._meshes[i].aabb);
        }
        this.aabbDirty = false;
    }
}
```

**Comment by xeolabs** [comment]
Fixed in 2.4.2-beta-42
